import Providers from '@/components/Providers/Providers';
import StoreProvider from '@/components/Redux/Redux';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Money Dream',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={inter.className}
        suppressHydrationWarning={true}
      >
        <Providers>
          <StoreProvider>{children}</StoreProvider>
          <Toaster
            toastOptions={{
              duration: 3000,
              style: {
                background: '#363636',
                color: '#fff'
              }
            }}
            gutter={8}
          />
        </Providers>
      </body>
    </html>
  );
}
